// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rebtel.LibraryManagement.Infrastructure;

#nullable disable

namespace Rebtel.LibraryManagement.Infrastructure.Migrations
{
    [DbContext(typeof(LibraryManagementContext))]
    partial class LibraryManagementContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookBorrowRecord", b =>
                {
                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BorrowRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BookId", "BorrowRecordId");

                    b.HasIndex("BorrowRecordId");

                    b.ToTable("BookBorrowRecord");

                    b.HasData(
                        new
                        {
                            BookId = new Guid("11111111-1111-1111-1111-111111111123"),
                            BorrowRecordId = new Guid("33333333-3333-3333-3333-000000000001")
                        },
                        new
                        {
                            BookId = new Guid("11111111-1111-1111-1111-111111111131"),
                            BorrowRecordId = new Guid("33333333-3333-3333-3333-000000000002")
                        },
                        new
                        {
                            BookId = new Guid("11111111-1111-1111-1111-111111111112"),
                            BorrowRecordId = new Guid("33333333-3333-3333-3333-000000000003")
                        },
                        new
                        {
                            BookId = new Guid("11111111-1111-1111-1111-111111111111"),
                            BorrowRecordId = new Guid("33333333-3333-3333-3333-000000000003")
                        },
                        new
                        {
                            BookId = new Guid("11111111-1111-1111-1111-111111111118"),
                            BorrowRecordId = new Guid("33333333-3333-3333-3333-000000000004")
                        },
                        new
                        {
                            BookId = new Guid("11111111-1111-1111-1111-111111111121"),
                            BorrowRecordId = new Guid("33333333-3333-3333-3333-000000000005")
                        },
                        new
                        {
                            BookId = new Guid("11111111-1111-1111-1111-111111111132"),
                            BorrowRecordId = new Guid("33333333-3333-3333-3333-000000000006")
                        },
                        new
                        {
                            BookId = new Guid("11111111-1111-1111-1111-111111111126"),
                            BorrowRecordId = new Guid("33333333-3333-3333-3333-000000000007")
                        },
                        new
                        {
                            BookId = new Guid("11111111-1111-1111-1111-111111111115"),
                            BorrowRecordId = new Guid("33333333-3333-3333-3333-000000000008")
                        },
                        new
                        {
                            BookId = new Guid("11111111-1111-1111-1111-111111111123"),
                            BorrowRecordId = new Guid("33333333-3333-3333-3333-000000000009")
                        },
                        new
                        {
                            BookId = new Guid("11111111-1111-1111-1111-111111111119"),
                            BorrowRecordId = new Guid("33333333-3333-3333-3333-000000000010")
                        },
                        new
                        {
                            BookId = new Guid("11111111-1111-1111-1111-111111111131"),
                            BorrowRecordId = new Guid("33333333-3333-3333-3333-000000000011")
                        },
                        new
                        {
                            BookId = new Guid("11111111-1111-1111-1111-111111111117"),
                            BorrowRecordId = new Guid("33333333-3333-3333-3333-000000000012")
                        },
                        new
                        {
                            BookId = new Guid("11111111-1111-1111-1111-111111111118"),
                            BorrowRecordId = new Guid("33333333-3333-3333-3333-000000000013")
                        },
                        new
                        {
                            BookId = new Guid("11111111-1111-1111-1111-111111111120"),
                            BorrowRecordId = new Guid("33333333-3333-3333-3333-000000000013")
                        },
                        new
                        {
                            BookId = new Guid("11111111-1111-1111-1111-111111111121"),
                            BorrowRecordId = new Guid("33333333-3333-3333-3333-000000000014")
                        },
                        new
                        {
                            BookId = new Guid("11111111-1111-1111-1111-111111111124"),
                            BorrowRecordId = new Guid("33333333-3333-3333-3333-000000000015")
                        },
                        new
                        {
                            BookId = new Guid("11111111-1111-1111-1111-111111111112"),
                            BorrowRecordId = new Guid("33333333-3333-3333-3333-000000000016")
                        },
                        new
                        {
                            BookId = new Guid("11111111-1111-1111-1111-111111111128"),
                            BorrowRecordId = new Guid("33333333-3333-3333-3333-000000000017")
                        },
                        new
                        {
                            BookId = new Guid("11111111-1111-1111-1111-111111111132"),
                            BorrowRecordId = new Guid("33333333-3333-3333-3333-000000000018")
                        },
                        new
                        {
                            BookId = new Guid("11111111-1111-1111-1111-111111111129"),
                            BorrowRecordId = new Guid("33333333-3333-3333-3333-000000000019")
                        },
                        new
                        {
                            BookId = new Guid("11111111-1111-1111-1111-111111111126"),
                            BorrowRecordId = new Guid("33333333-3333-3333-3333-000000000020")
                        },
                        new
                        {
                            BookId = new Guid("11111111-1111-1111-1111-111111111133"),
                            BorrowRecordId = new Guid("33333333-3333-3333-3333-000000000021")
                        },
                        new
                        {
                            BookId = new Guid("11111111-1111-1111-1111-111111111123"),
                            BorrowRecordId = new Guid("33333333-3333-3333-3333-000000000022")
                        },
                        new
                        {
                            BookId = new Guid("11111111-1111-1111-1111-111111111134"),
                            BorrowRecordId = new Guid("33333333-3333-3333-3333-000000000023")
                        },
                        new
                        {
                            BookId = new Guid("11111111-1111-1111-1111-111111111131"),
                            BorrowRecordId = new Guid("33333333-3333-3333-3333-000000000024")
                        },
                        new
                        {
                            BookId = new Guid("11111111-1111-1111-1111-111111111135"),
                            BorrowRecordId = new Guid("33333333-3333-3333-3333-000000000025")
                        },
                        new
                        {
                            BookId = new Guid("11111111-1111-1111-1111-111111111121"),
                            BorrowRecordId = new Guid("33333333-3333-3333-3333-000000000026")
                        },
                        new
                        {
                            BookId = new Guid("11111111-1111-1111-1111-111111111122"),
                            BorrowRecordId = new Guid("33333333-3333-3333-3333-000000000026")
                        },
                        new
                        {
                            BookId = new Guid("11111111-1111-1111-1111-111111111118"),
                            BorrowRecordId = new Guid("33333333-3333-3333-3333-000000000027")
                        },
                        new
                        {
                            BookId = new Guid("11111111-1111-1111-1111-111111111113"),
                            BorrowRecordId = new Guid("33333333-3333-3333-3333-000000000028")
                        },
                        new
                        {
                            BookId = new Guid("11111111-1111-1111-1111-111111111112"),
                            BorrowRecordId = new Guid("33333333-3333-3333-3333-000000000029")
                        },
                        new
                        {
                            BookId = new Guid("11111111-1111-1111-1111-111111111114"),
                            BorrowRecordId = new Guid("33333333-3333-3333-3333-000000000030")
                        },
                        new
                        {
                            BookId = new Guid("11111111-1111-1111-1111-111111111132"),
                            BorrowRecordId = new Guid("33333333-3333-3333-3333-000000000031")
                        },
                        new
                        {
                            BookId = new Guid("11111111-1111-1111-1111-111111111126"),
                            BorrowRecordId = new Guid("33333333-3333-3333-3333-000000000032")
                        },
                        new
                        {
                            BookId = new Guid("11111111-1111-1111-1111-111111111116"),
                            BorrowRecordId = new Guid("33333333-3333-3333-3333-000000000033")
                        },
                        new
                        {
                            BookId = new Guid("11111111-1111-1111-1111-111111111123"),
                            BorrowRecordId = new Guid("33333333-3333-3333-3333-000000000034")
                        },
                        new
                        {
                            BookId = new Guid("11111111-1111-1111-1111-111111111127"),
                            BorrowRecordId = new Guid("33333333-3333-3333-3333-000000000034")
                        },
                        new
                        {
                            BookId = new Guid("11111111-1111-1111-1111-111111111131"),
                            BorrowRecordId = new Guid("33333333-3333-3333-3333-000000000035")
                        });
                });

            modelBuilder.Entity("Rebtel.LibraryManagement.Domain.Aggregates.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("CopiesAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PageCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Author");

                    b.HasIndex("ISBN")
                        .IsUnique();

                    b.HasIndex("PublishedDate");

                    b.HasIndex("Title");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Author = "Harper Lee",
                            CopiesAvailable = 5,
                            ISBN = "978-0-06-112008-4",
                            PageCount = 324,
                            PublishedDate = new DateTime(1960, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            Author = "George Orwell",
                            CopiesAvailable = 3,
                            ISBN = "978-0-452-28423-4",
                            PageCount = 328,
                            PublishedDate = new DateTime(1949, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "1984"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111113"),
                            Author = "Jane Austen",
                            CopiesAvailable = 4,
                            ISBN = "978-0-14-143951-8",
                            PageCount = 432,
                            PublishedDate = new DateTime(1813, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111114"),
                            Author = "F. Scott Fitzgerald",
                            CopiesAvailable = 6,
                            ISBN = "978-0-7432-7356-5",
                            PageCount = 180,
                            PublishedDate = new DateTime(1925, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111115"),
                            Author = "J.D. Salinger",
                            CopiesAvailable = 2,
                            ISBN = "978-0-316-76948-0",
                            PageCount = 277,
                            PublishedDate = new DateTime(1951, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Catcher in the Rye"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111116"),
                            Author = "Frank Herbert",
                            CopiesAvailable = 4,
                            ISBN = "978-0-441-17271-9",
                            PageCount = 688,
                            PublishedDate = new DateTime(1965, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Dune"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111117"),
                            Author = "Isaac Asimov",
                            CopiesAvailable = 3,
                            ISBN = "978-0-553-29335-6",
                            PageCount = 244,
                            PublishedDate = new DateTime(1951, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Foundation"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111118"),
                            Author = "Douglas Adams",
                            CopiesAvailable = 5,
                            ISBN = "978-0-345-39180-3",
                            PageCount = 224,
                            PublishedDate = new DateTime(1979, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Hitchhiker's Guide to the Galaxy"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111119"),
                            Author = "William Gibson",
                            CopiesAvailable = 2,
                            ISBN = "978-0-441-56956-9",
                            PageCount = 271,
                            PublishedDate = new DateTime(1984, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Neuromancer"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111120"),
                            Author = "Orson Scott Card",
                            CopiesAvailable = 4,
                            ISBN = "978-0-812-55070-2",
                            PageCount = 324,
                            PublishedDate = new DateTime(1985, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Ender's Game"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111121"),
                            Author = "J.R.R. Tolkien",
                            CopiesAvailable = 6,
                            ISBN = "978-0-547-92822-7",
                            PageCount = 366,
                            PublishedDate = new DateTime(1937, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Hobbit"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111122"),
                            Author = "J.R.R. Tolkien",
                            CopiesAvailable = 3,
                            ISBN = "978-0-547-92821-0",
                            PageCount = 479,
                            PublishedDate = new DateTime(1954, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Fellowship of the Ring"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111123"),
                            Author = "J.K. Rowling",
                            CopiesAvailable = 8,
                            ISBN = "978-0-7475-3269-9",
                            PageCount = 223,
                            PublishedDate = new DateTime(1997, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Harry Potter and the Philosopher's Stone"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111124"),
                            Author = "George R.R. Martin",
                            CopiesAvailable = 5,
                            ISBN = "978-0-553-10354-0",
                            PageCount = 694,
                            PublishedDate = new DateTime(1996, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "A Game of Thrones"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111125"),
                            Author = "Patrick Rothfuss",
                            CopiesAvailable = 3,
                            ISBN = "978-0-7564-0474-1",
                            PageCount = 662,
                            PublishedDate = new DateTime(2007, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Name of the Wind"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111126"),
                            Author = "Stieg Larsson",
                            CopiesAvailable = 4,
                            ISBN = "978-0-307-45454-1",
                            PageCount = 590,
                            PublishedDate = new DateTime(2005, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Girl with the Dragon Tattoo"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111127"),
                            Author = "Gillian Flynn",
                            CopiesAvailable = 3,
                            ISBN = "978-0-307-58836-4",
                            PageCount = 419,
                            PublishedDate = new DateTime(2012, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Gone Girl"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111128"),
                            Author = "Dan Brown",
                            CopiesAvailable = 5,
                            ISBN = "978-0-307-47492-1",
                            PageCount = 489,
                            PublishedDate = new DateTime(2003, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Da Vinci Code"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111129"),
                            Author = "Agatha Christie",
                            CopiesAvailable = 4,
                            ISBN = "978-0-06-207348-6",
                            PageCount = 264,
                            PublishedDate = new DateTime(1939, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "And Then There Were None"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111130"),
                            Author = "Raymond Chandler",
                            CopiesAvailable = 2,
                            ISBN = "978-0-394-75828-5",
                            PageCount = 231,
                            PublishedDate = new DateTime(1939, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Big Sleep"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111131"),
                            Author = "Yuval Noah Harari",
                            CopiesAvailable = 6,
                            ISBN = "978-0-062-31609-6",
                            PageCount = 443,
                            PublishedDate = new DateTime(2011, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Sapiens: A Brief History of Humankind"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111132"),
                            Author = "Tara Westover",
                            CopiesAvailable = 7,
                            ISBN = "978-0-399-59050-4",
                            PageCount = 334,
                            PublishedDate = new DateTime(2018, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Educated"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111133"),
                            Author = "Rebecca Skloot",
                            CopiesAvailable = 3,
                            ISBN = "978-1-400-05217-2",
                            PageCount = 381,
                            PublishedDate = new DateTime(2010, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Immortal Life of Henrietta Lacks"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111134"),
                            Author = "Daniel Kahneman",
                            CopiesAvailable = 4,
                            ISBN = "978-0-374-53355-7",
                            PageCount = 499,
                            PublishedDate = new DateTime(2011, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Thinking, Fast and Slow"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111135"),
                            Author = "Charles Duhigg",
                            CopiesAvailable = 5,
                            ISBN = "978-1-400-06928-6",
                            PageCount = 371,
                            PublishedDate = new DateTime(2012, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Power of Habit"
                        });
                });

            modelBuilder.Entity("Rebtel.LibraryManagement.Domain.Aggregates.BorrowRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BorrowDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BorrowRecords");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000001"),
                            BorrowDate = new DateTime(2022, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2022, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("22222222-2222-2222-2222-222222222221")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000002"),
                            BorrowDate = new DateTime(2022, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2022, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000003"),
                            BorrowDate = new DateTime(2022, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("22222222-2222-2222-2222-222222222223")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000004"),
                            BorrowDate = new DateTime(2022, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2022, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("22222222-2222-2222-2222-222222222224")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000005"),
                            BorrowDate = new DateTime(2022, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2022, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("22222222-2222-2222-2222-222222222225")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000006"),
                            BorrowDate = new DateTime(2022, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2022, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("22222222-2222-2222-2222-222222222226")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000007"),
                            BorrowDate = new DateTime(2022, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2022, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("22222222-2222-2222-2222-222222222227")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000008"),
                            BorrowDate = new DateTime(2022, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2022, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("22222222-2222-2222-2222-222222222228")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000009"),
                            BorrowDate = new DateTime(2022, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2022, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("22222222-2222-2222-2222-222222222229")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000010"),
                            BorrowDate = new DateTime(2022, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2022, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("22222222-2222-2222-2222-222222222230")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000011"),
                            BorrowDate = new DateTime(2023, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2023, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("22222222-2222-2222-2222-222222222231")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000012"),
                            BorrowDate = new DateTime(2023, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2023, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("22222222-2222-2222-2222-222222222232")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000013"),
                            BorrowDate = new DateTime(2023, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2023, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("22222222-2222-2222-2222-222222222233")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000014"),
                            BorrowDate = new DateTime(2023, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2023, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("22222222-2222-2222-2222-222222222234")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000015"),
                            BorrowDate = new DateTime(2023, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2023, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("22222222-2222-2222-2222-222222222235")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000016"),
                            BorrowDate = new DateTime(2023, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2023, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("22222222-2222-2222-2222-222222222236")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000017"),
                            BorrowDate = new DateTime(2023, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2023, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("22222222-2222-2222-2222-222222222237")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000018"),
                            BorrowDate = new DateTime(2023, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2023, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("22222222-2222-2222-2222-222222222238")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000019"),
                            BorrowDate = new DateTime(2023, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2023, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("22222222-2222-2222-2222-222222222239")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000020"),
                            BorrowDate = new DateTime(2023, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2023, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("22222222-2222-2222-2222-222222222240")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000021"),
                            BorrowDate = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2024, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("22222222-2222-2222-2222-222222222221")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000022"),
                            BorrowDate = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2024, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000023"),
                            BorrowDate = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2024, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("22222222-2222-2222-2222-222222222223")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000024"),
                            BorrowDate = new DateTime(2024, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2024, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("22222222-2222-2222-2222-222222222224")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000025"),
                            BorrowDate = new DateTime(2024, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2024, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("22222222-2222-2222-2222-222222222225")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000026"),
                            BorrowDate = new DateTime(2024, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2024, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("22222222-2222-2222-2222-222222222226")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000027"),
                            BorrowDate = new DateTime(2024, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2024, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("22222222-2222-2222-2222-222222222227")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000028"),
                            BorrowDate = new DateTime(2024, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2024, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("22222222-2222-2222-2222-222222222228")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000029"),
                            BorrowDate = new DateTime(2024, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2024, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("22222222-2222-2222-2222-222222222229")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000030"),
                            BorrowDate = new DateTime(2024, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2024, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("22222222-2222-2222-2222-222222222230")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000031"),
                            BorrowDate = new DateTime(2024, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("22222222-2222-2222-2222-222222222231")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000032"),
                            BorrowDate = new DateTime(2024, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("22222222-2222-2222-2222-222222222232")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000033"),
                            BorrowDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("22222222-2222-2222-2222-222222222233")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000034"),
                            BorrowDate = new DateTime(2024, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("22222222-2222-2222-2222-222222222234")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000035"),
                            BorrowDate = new DateTime(2024, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("22222222-2222-2222-2222-222222222235")
                        });
                });

            modelBuilder.Entity("Rebtel.LibraryManagement.Domain.Aggregates.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateTime>("MembershipDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MembershipDate");

                    b.HasIndex("Name");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222221"),
                            Email = "emma.johnson@email.com",
                            MembershipDate = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Emma Johnson",
                            PhoneNumber = "+1-555-0101"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Email = "michael.chen@email.com",
                            MembershipDate = new DateTime(2019, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Michael Chen",
                            PhoneNumber = "+1-555-0102"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222223"),
                            Email = "sarah.williams@email.com",
                            MembershipDate = new DateTime(2021, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sarah Williams",
                            PhoneNumber = "+1-555-0103"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222224"),
                            Email = "david.rodriguez@email.com",
                            MembershipDate = new DateTime(2018, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "David Rodriguez",
                            PhoneNumber = "+1-555-0104"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222225"),
                            Email = "lisa.anderson@email.com",
                            MembershipDate = new DateTime(2020, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lisa Anderson",
                            PhoneNumber = "+1-555-0105"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222226"),
                            Email = "james.wilson@email.com",
                            MembershipDate = new DateTime(2019, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "James Wilson",
                            PhoneNumber = "+1-555-0106"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222227"),
                            Email = "maria.garcia@email.com",
                            MembershipDate = new DateTime(2022, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Maria Garcia",
                            PhoneNumber = "+1-555-0107"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222228"),
                            Email = "robert.taylor@email.com",
                            MembershipDate = new DateTime(2017, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Robert Taylor",
                            PhoneNumber = "+1-555-0108"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222229"),
                            Email = "jennifer.brown@email.com",
                            MembershipDate = new DateTime(2021, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jennifer Brown",
                            PhoneNumber = "+1-555-0109"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222230"),
                            Email = "christopher.davis@email.com",
                            MembershipDate = new DateTime(2020, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Christopher Davis",
                            PhoneNumber = "+1-555-0110"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222231"),
                            Email = "amanda.miller@email.com",
                            MembershipDate = new DateTime(2018, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Amanda Miller",
                            PhoneNumber = "+1-555-0111"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222232"),
                            Email = "daniel.lee@email.com",
                            MembershipDate = new DateTime(2019, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Daniel Lee",
                            PhoneNumber = "+1-555-0112"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222233"),
                            Email = "ashley.martinez@email.com",
                            MembershipDate = new DateTime(2021, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ashley Martinez",
                            PhoneNumber = "+1-555-0113"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222234"),
                            Email = "matthew.white@email.com",
                            MembershipDate = new DateTime(2022, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Matthew White",
                            PhoneNumber = "+1-555-0114"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222235"),
                            Email = "jessica.thompson@email.com",
                            MembershipDate = new DateTime(2017, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jessica Thompson",
                            PhoneNumber = "+1-555-0115"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222236"),
                            Email = "andrew.jackson@email.com",
                            MembershipDate = new DateTime(2020, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Andrew Jackson",
                            PhoneNumber = "+1-555-0116"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222237"),
                            Email = "nicole.harris@email.com",
                            MembershipDate = new DateTime(2019, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Nicole Harris",
                            PhoneNumber = "+1-555-0117"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222238"),
                            Email = "joshua.clark@email.com",
                            MembershipDate = new DateTime(2021, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Joshua Clark",
                            PhoneNumber = "+1-555-0118"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222239"),
                            Email = "stephanie.lewis@email.com",
                            MembershipDate = new DateTime(2018, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Stephanie Lewis",
                            PhoneNumber = "+1-555-0119"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222240"),
                            Email = "ryan.walker@email.com",
                            MembershipDate = new DateTime(2022, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ryan Walker",
                            PhoneNumber = "+1-555-0120"
                        });
                });

            modelBuilder.Entity("BookBorrowRecord", b =>
                {
                    b.HasOne("Rebtel.LibraryManagement.Domain.Aggregates.Book", null)
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rebtel.LibraryManagement.Domain.Aggregates.BorrowRecord", null)
                        .WithMany()
                        .HasForeignKey("BorrowRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Rebtel.LibraryManagement.Domain.Aggregates.BorrowRecord", b =>
                {
                    b.HasOne("Rebtel.LibraryManagement.Domain.Aggregates.User", "User")
                        .WithMany("BorrowRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rebtel.LibraryManagement.Domain.Aggregates.User", b =>
                {
                    b.Navigation("BorrowRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
